apiVersion: v1
kind: Service
metadata:
  name: customerservice-service
spec:
  type: NodePort
  selector:
    app: customerservice
  ports:
    - protocol: TCP
      nodePort: 30085
      port: 9005
      targetPort: 9005