apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-deployment
spec:
  selector:
    matchLabels:
      app: customerservice
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
      - image: us.icr.io/sriniatmakurns/customerservice:1.0
        name: customerservice
        imagePullPolicy: Always
        ports:
        - containerPort: 9005  
        volumeMounts:
        - name: customerservice-volume
          mountPath: "/config"
      restartPolicy: Always
      volumes:
      - name: customerservice-volume
        configMap:
          name: customerservicecm
          items:
          - key: application.properties
            path: application.properties
